# version: "3"
# services:
#   postgres:
#     image: "postgres:15.2-alpine3.17"
#     ports:
#       - "55432:5432"
#     environment:
#       POSTGRES_USER: "user"
#       POSTGRES_PASSWORD: "0000"
#       POSTGRES_DB: "bot"

version: "3.9"
services:
  db:
    image: "postgres:15.2-alpine3.17"
    environment:
      POSTGRES_USER: "botuser"
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: "bot"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    environment:
      PORT: "3000"
      POSTGRES_USER: "botuser"
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: "bot"
      POSTGRES_PORT: 5432
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres-data:
